temporary_downloadable_media.settings:
  type: config_object
  label: 'Temporary Downloadable Media Settings'
  mapping:
    user_select:
      type: string
      label: 'select user to generate a valid token'
